# Generated by Django 3.2.6 on 2021-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cost_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100)),
                ('report_desc', models.CharField(max_length=200)),
                ('report_date', models.DateField(verbose_name='date of report')),
            ],
        ),
    ]
